version: '3'

services:

  web:
    image: localhost:5000/stackdemo
    build: .
    ports:
      - "8000:8000"
    deploy:
      placement:
        constraints:
          - node.role == worker
      
  redis:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - node.role == worker